### ISSUE TITLE
Is WooCommerceConnector GPLv3 or AGPL

### ISSUE THREAD

**Issue by PiotrCzapla** [libracore/WooCommerceConnector#21]
Hi,

The repo says the code is licensed under GPLv3 which would be good as it matches ERPNext, licensing, but the README says AGPL could you clarify if your code can be used as GPLv3? 

Following the GPLv3 restriction in corporate world is hard already having a mixture of AGPL and GPLv3 makes things more complicated. 

Would you consider following the same license as ERPNext?

**Comment by lasalesi** [comment]
The app is classified as AGPL, which is the somewhat improved version of GPL. Refer to https://www.gnu.org/licenses/why-affero-gpl.en.html

So technically, AGPL (especiall with respect to a cloud platform) is actually the better way. The only restriction over GPL is that when used in a hosted environment, you have to disclose the code.

I cannot see the concern regarding the use...

I would even suggest to have ERPNext as AGPL...
