### ISSUE TITLE
WooCommerceConnector Settings error

### ISSUE THREAD

**Issue by EnSeal** [libracore/WooCommerceConnector#22]
Hello 

I have been trying to use this on my ERPNext and i seem not to be able to use the app after installation..

Below is a screenshot of the page after clicking on woocommerce settings

![image](https://user-images.githubusercontent.com/18033246/73677282-2f503800-46b6-11ea-80c9-450409ebe36f.png)

**Comment by carstenblt** [comment]
Renaming the DocType indeed at least makes it accessible. I guess it would be good practice anyways not to overwrite the core type.

**Comment by lasalesi** [comment]
Needs to be renamed for compatibility as the V12  uses the same name for another module (integrations)...

**Comment by lasalesi** [comment]
Please check back, should be resolved with #23
