### ISSUE TITLE
InternalError(1054, "Unknown column 'barcode' in 'where clause'"),

### ISSUE THREAD

**Issue by gsarunk** [libracore/WooCommerceConnector#26]
Getting the error while doing 'Sync Woocommerce Id to ERP'.
Error:
![image](https://user-images.githubusercontent.com/37296111/83356382-71973680-a383-11ea-8f15-76ba33270cd6.png)

Actual Place of Dump
![image](https://user-images.githubusercontent.com/37296111/83356424-b91dc280-a383-11ea-9fec-5b4f725adf07.png)

Possible reason: field  name 'barcode' should be replaced with 'barcodes'
![image](https://user-images.githubusercontent.com/37296111/83356464-01d57b80-a384-11ea-8875-4b55312da2a0.png)

Your response and fix awaited and Much appreciated

**Comment by lasalesi** [comment]
ERPNext has dropped the `tabItem`.`barcode` field in v12. Earlier installations will still have this.

To correct this, simply add (using Menu > Customize) a barcode field again to the Item doctype. You can fill this from e.g. the first line of the barcodes table (optionally).

I will make a note to add the barcode field in the item customisations for compatibility.

**Comment by lasalesi** [comment]
This should be included in the app customzation now (b200df5)

You can run bench update and this should be resolved
