### ISSUE TITLE
Server error when trying to same setting in ERPNExt v12

### ISSUE THREAD

**Issue by jesseframework** [libracore/WooCommerceConnector#30]
![image](https://user-images.githubusercontent.com/61049847/89926453-8d605980-dbca-11ea-9e4e-674c84b01f4c.png)

**Comment by jesseframework** [comment]
Am willing to pay to fix this issues can you help urgently.

**Comment by lasalesi** [comment]
Do you have an error trace? When does this error appear?

**Comment by jesseframework** [comment]
No. But you can access ERPNext
You can logon and check in my instant
UserName: woocommers@woocommers.com
Password: Woocommers
Link http://portal.maticautomotive.com/

I setup everything base on instruction
In WooCommers
 
![image](https://user-images.githubusercontent.com/61049847/90640183-49d2a480-e1f5-11ea-88fe-d2bb845ac21d.png)


In ERPNext

 
![image](https://user-images.githubusercontent.com/61049847/90640239-5ce57480-e1f5-11ea-9774-e0509db2c215.png)


 

When I click save

**Comment by lasalesi** [comment]
Root cause was that the REST API was not accessible because in WooCommerce, permalinks were not active.

Check the REST API under https://yourhost/wp-json

If you get no response, make sure that Settings > Permalinks are enabled.
