### ISSUE TITLE
Uninstalling WooCommerce connector may mess up product groups

### ISSUE THREAD

**Issue by pfrydlewicz** [libracore/WooCommerceConnector#38]
Hi, after trying out the woocommerce connector, I tried to uninstall the app, which went fine using the bench command.
However, afterwards I get following error when opening my item list view:

"DocType Item Product Category not found"

Can you please advice?
Thank you

**Comment by lasalesi** [comment]
This is a remainder of the field customisations, that the bench toolkit does not properly remove. WooCommerceConnector will add this field. Go to "Custom Field" List and remove the mentioned Link field.
