### ISSUE TITLE
Installation: Module import failed for Asset Settings

### ISSUE THREAD

**Issue by rasos** [libracore/WooCommerceConnector#51]
When installing the woocommerce app in a multi-site setup with 

         bench --site erpnext.ourcoop.com install-app woocommerceconnector 

we get

```
Installing woocommerceconnector...
Updating DocTypes for woocommerceconnector: [========================================] 100%
An error occurred while installing woocommerceconnector:
Module import failed for Asset Settings (erpnext.assets.doctype.asset_settings.asset_settings Error: No module named 'erpnext.assets.doctype.asset_settings.asset_settings')
```

Applying install command the second time does not throw that error anymore and the woocommerce app seems to work fine.

#48

**Comment by lasalesi** [comment]
This error is not caused in relation to WooComemrceConnector (it has no reference to erpnext.assets.doctype.asset_settings.asset_settings). However, it is caused by a previous ERPNext migration issue, which is pending and triggered at the app installation (would happen with any app).
