### ISSUE TITLE
ERPNext V13 Support

### ISSUE THREAD

**Issue by Ahmed-M-Fawzy** [libracore/WooCommerceConnector#56]
HI Libacore
Is it planned to support ERPNext V13

**Comment by lasalesi** [comment]
Thanks for your feedback. Currently, we are waiting for a better robustness of v13. But this is open source, please feel free to send in a PR...

**Comment by germanllop** [comment]
Hey there, any point where to start? v13 is already the stable release, v14beta is already being worked.

**Comment by nasirrr** [comment]
It is working for v13, with minor bugs here and there. I am using in Testing Environment it currently, and if all goes well would shift to Production

**Comment by germanllop** [comment]
> It is working for v13, with minor bugs here and there. I am using in Testing Environment it currently, and if all goes well would shift to Production

Good to know, I will check it out this week, will circle back here after testing.

**Comment by nasirrr** [comment]
That's Great! Will be waiting.

**Comment by germanllop** [comment]
> That's Great! Will be waiting.

So, got it working and fixed some bugs, I have one still when syncronizing the orders, it's tax realted, maybe you had it:

pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'b'IGV' ORDER BY `modified` DESC LIMIT 1' at line 1")

IGV is my sales Tax (VAT), it's already mapped, even if I delete the mapping it will throw the error.

**Comment by sptechcue** [comment]
The connector is functional in ERPNext v13, correctly synchronizes products and their variants, imports orders and customers into ERPNext.

**Comment by germanllop** [comment]
> The connector is functional in ERPNext v13, correctly synchronizes products and their variants, imports orders and customers into ERPNext.

There is any TAX and Shipping on WooCommerce?, I think there's an issue there.

**Comment by nasirrr** [comment]
Yes. You would have to configure it in woocommerce. And then try to import the invoices. It takes some trial and error, but should be doable.

**Comment by germanllop** [comment]
> Yes. You would have to configure it in woocommerce. And then try to import the invoices. It takes some trial and error, but should be doable.

What do you mean to configure it? Like, both have to be named the same, right? Just that?
