### ISSUE TITLE
Sync Issue

### ISSUE THREAD

**Issue by alpelectronics** [libracore/WooCommerceConnector#62]
Hi,

When I try to sync from ERPNext to WooCommerce I get the following errors for the items. I couldnt find a way to fix it. 

![image](https://user-images.githubusercontent.com/10106458/184649173-b16ad04d-e42c-4630-90c4-1b963ada55ec.png)

**Comment by lasalesi** [comment]
As the message indicates, please sync the WooCommerce IDs. Your current configuration has no WooCommerce Product IDs, these are required to map products from ERPNext to WooCommerce.

Once you have cleaned your data, it will work.
